/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ijackprovostjr (https://sketchfab.com/ijackprovostjr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-cynthia-ee56229e1fe3425cb30c3099df966ae4
Title: Pokemon Cynthia
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cyntia(props) {
  const { nodes, materials } = useGLTF('models/cynthia.glb')
  return (
    <group {...props} dispose={null} scale={0.28}>
      <group rotation={[Math.PI / 2.2, 0, 0]} scale={0.04} position={[0, -1, -15]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials['tr0052_00_BodyB_tga-material']}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials['tr0052_00_BodyA_tga-material']}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials['tr0052_00_Eye_tga-material']}
          skeleton={nodes.Object_11.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/cynthia.glb')